### ISSUE TITLE
你好，请教一下训练相关的问题

### ISSUE THREAD

**Issue by SeniorGlassMaster** [Macielyoung/T5Corrector#11]
1、使用trainer\pretrain.py进行自有语料的训练时，训练时数据的格式是怎样的呢？
2、rawdata\stock.txt中的这个文件中是什么用途呢？如何替换成自己的数据呢？

**Comment by Macielyoung** [comment]
1. 数据中有source和target句对就行了，source是原始文本，target是纠错后的文本（也可能没有错误）

**Comment by Macielyoung** [comment]
1. 数据中有source和target句对就行了，source是原始文本，target是纠错后的文本（也可能没有错误）

**Comment by Macielyoung** [comment]
1. 数据中有source和target句对就行了，source是原始文本，target是纠错后的文本（也可能没有错误）
2. stock是用来构造关于股票名称相关的语料的，可以理解为垂直领域语料

**Comment by SeniorGlassMaster** [comment]
点赞！

**Comment by cristianohello** [comment]
@SeniorGlassMaster @Macielyoung 你好，训练集能提供吗》多谢
