### ISSUE TITLE
请教作者，针对包含停顿语助词的句子

### ISSUE THREAD

**Issue by jeremy110** [Macielyoung/T5Corrector#7]
作者你好，我想应用你的model在ASR之后，我想去除掉一些停顿语气的语助词，如以下范例，不知道你有没有试过?
或者能不能给我些建议? 十分感谢。

范例: 嗯，我们今天要讨论那个新的计划。
纠错後: 我们今天要讨论那个新的计划。

**Comment by Macielyoung** [comment]
这个增加对应语料在checkpoint基础上继续训练就好了，找到符合你场景的平行语料比较重要，输入样本就是用你的ASR输出的句子，可以利用GPT生成改写后的样本，或者利用一些优质的开源大模型（比如qwen-72B-chat）去生成。

**Comment by jeremy110** [comment]
好的，十分感谢， 我再试试
